name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      FLUTTER_GIT_URL: https://github.com/flutter/flutter.git

    steps:
      - name: Checkout repository (including submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Set up Flutter SDK path
        run: echo "$(pwd)/submodules/flutter/bin" >> $GITHUB_PATH

      - name: Display Flutter version
        run: flutter channel master

      - name: Display Flutter version
        run: flutter --version

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Upgrade Flutter Dependencies
        run: flutter pub upgrade
        
      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
