name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Checkout repository (including submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --init --recursive --remote
          
      - name: Set up Flutter SDK path
        run: echo "$(pwd)/submodules/flutter/bin" >> $GITHUB_PATH

      - name: Switch Flutter channel
        run: flutter channel master --disable-analytics

      - name: Switch Flutter channel
        run: flutter upgrade
        
      - name: Display Flutter version
        run: flutter --version

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Upgrade Flutter Dependencies
        run: flutter pub upgrade
        
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
